lineages_to_simulate: 1
generations_to_simulate: 500
nucleosomeNumber: 1000
initialDensity: 0.02
dilutionBias: 0.5
replenish_rounds: 3
sigma: 3  # standard deviation of weight function (Gaussian)
alpha: 0.4  # arbitrary parameter
beta: 0.0001  # noise

